name: CI
on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  pull_request:
    types:
      - closed
  
  #to trigger CI manually
  workflow_dispatch:

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
        
    permissions:
      id-token: write
      contents: read
      
    steps:
      - uses: actions/checkout@v3

      - name: Provide permission
        run: chmod +x cf-change-set.sh
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC
          role-duration-seconds: 3600
          
      - name: Run script
        run: ./cf-change-set.sh
        
      - name: Get the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: get-artifacts
          path: artifacts-*
          
      - run: echo 'PR is merged'
